### ISSUE TITLE
Cannot open Doido Engine on Linux

### ISSUE THREAD

**Issue by Stefan2008Git** [DoidoTeam/FNF-Doido-Engine#10]
### Describe your problem here.

I don't really know why is doing this. Do i am missing something?
Here is a logs if you need
```
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 26
Called from ApplicationMain::create ApplicationMain.hx line 35
Called from ManifestResources::init ManifestResources.hx line 71
Called from openfl.text.Font::registerFont openfl/text/Font.hx line 251
Called from Type::createInstance /opt/hostedtoolcache/haxe/4.3.3/x64/std/cpp/_std/Type.hx line 90
Called from __ASSET__OPENFL__assets_fonts_pixel_otf::new ManifestResources.hx line 535
Called from openfl.text.Font::new openfl/text/Font.hx line 60
Called from lime.text.Font::new lime/text/Font.hx line 97
Called from lime.text.Font::__fromFile lime/text/Font.hx line 464
Error : Invalid UTF16
```

Here is a image in case if image is better. Opened and runned directly from terminal
![image](https://github.com/user-attachments/assets/86ff7ba0-5ba1-4276-8021-e1b537adba5d)

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't. Downloaded the frash release build from GitHub release page

**Comment by iamteles** [comment]
Interesting... what distro is this?

**Comment by Stefan2008Git** [comment]
> Interesting... what distro is this?

Base Arch Linux with KDE 6.2.0 installed (I use Arch btw)

**Comment by Stefan2008Git** [comment]
> > Interesting... what distro is this?
> 
> Base Arch Linux with KDE 6.2.0 installed (I use Arch btw)

Also i figured out it can be the latest Lime with UTF thing

**Comment by iamteles** [comment]
The build is working for me on Ubuntu 24.04.1 LTS, both opening it from the file manager and from the terminal, so maybe lime has issues running on Arch, which I currently have no way to test it on, so i'm afraid i wont be able to resolve this myself. Maybe you should try building the mod yourself if possible?

**Comment by Stefan2008Git** [comment]
> The build is working for me on Ubuntu 24.04.1 LTS, both opening it from the file manager and from the terminal, so maybe lime has issues running on Arch, which I currently have no way to test it on, so i'm afraid i wont be able to resolve this myself. Maybe you should try building the mod yourself if possible?

...
Yeah, i should manually compile your engine then..
But thank you anyways
