### ISSUE TITLE
i cant tell if this is due to a bad haxe install

### ISSUE THREAD

**Issue by HTGM1** [DoidoTeam/FNF-Doido-Engine#11]
### What is your question?

i cant tell if this is due to a bad haxe install, made a fresh folder with no changes to the source, and only when playing story mode stuff, when it reaches the end of the week, it crashes due to pulling something from my haxe toolkit, which results it trying to pull from a song called null which means something isn't pulling correctly

mostly am new with this engine, but now i know its not a me messing up code issue, but idk if it stems from a haxe 3.3.3 issue or if i have bad install of something in the toolkit directory
![Screenshot 2024-10-13 152622](https://github.com/user-attachments/assets/e2ec4c1b-c4f3-4edf-8f87-e405cb01c775)

**Comment by HTGM1** [comment]
again it only seems to happen when doing a story mode week and reaching the end of said week, freeplay doesn't seem to have this same null crash

**Comment by iamteles** [comment]
Probably our story mode is broken. We will look into this.

On another note, your haxe install is most likely fine and the haxe class it pulls is just because the game tries to find a "null" chart and fails, so no need to do anything

**Comment by iamteles** [comment]
Alright this is fixed now. You can either pull the engine again or manually do this fix by doing like this image
![image](https://github.com/user-attachments/assets/9f4f30cd-cec8-4c3d-a52a-593ae1be1006)

**Comment by HTGM1** [comment]
thanks very much!
