### ISSUE TITLE
Tutorial Camera jank after changing chart

### ISSUE THREAD

**Issue by HTGM1** [DoidoTeam/FNF-Doido-Engine#15]
after attempting to change tutorial charts, the hard coded cam stuff broke, and i didn't mess with anything other the just the chart

currently a temp fix i did was disable the camera that was setup for that and implemented identical camera zooms into the chart i was working on, which may be a better thing to do, idk if its the cause of bumping the framerate up as well, forgot to really test that after finding a fix for myself

footage is before the temp fix on what i mean by "Camera jank" (ignore that the audio is silent, forgot to change some settings in OBS)

https://github.com/user-attachments/assets/8b34ed0b-7778-4e3b-bebe-a42c00fdf052

Granted, i did decide to disable the camera case for the tutorial stuff and use the camera zoom event as a fix, so granted its not really a big worry, but i thought i might as well bring this up to say that this is a bug that is cause just by changing the chart (for some reason(haven't checked much around the chart files yet other then Erect Remix charts))

hopefully this issue isn't a big deal and that you guys have a excellent day ^^

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing related to the issue, but there are some obvious changes to the gameObjects (oh and the chart for tutorial)

**Comment by iamteles** [comment]
pretty sure this has been an issue for a while and happens regardless of editing the chart or not

**Comment by iamteles** [comment]
Alright, this should be fixed in the latest commits (there's two cause i forgot to test something lol). Basically what we did was change the tween that changes the zoom to be our custom camera lerp instead (and also moved that function to CoolUtil)
![image](https://github.com/user-attachments/assets/57f4c845-4404-48a1-bb4f-a3129804b1e7)

**Comment by HTGM1** [comment]
really, huh i never saw it freak before tho until i changed the chart, but as long as things are looking good then that's good ^^

ill try to bring forward the changes later when i start working on my stuff again
