### ISSUE TITLE
a built-in "Play Stage Animation" event

### ISSUE THREAD

**Issue by HTGM1** [DoidoTeam/FNF-Doido-Engine#16]
### What feature do you want to see added to the engine?

was thinking on this one for a bit, a built in "Play Stage Animation" for this engine would be cool, planning on custom coding one for my forks for some stuff cause I'm planning to do a lot of stage stuff for some projects

the idea is basically similar too the Normal "Play Animation" event, but just with stage objects that have animations defined for them

this would allow for flexibility for many people to make timed stage events with just sprite sheets

an example would be like having a lightning strike happen on screen for if its on the stage but has its idle animation playing (which would be blank) and having the event call on its 2nd animation to play the strike

**Comment by iamteles** [comment]
since you gotta declare your own stage objects in the Stage class this would not be something that could be easily done and implemented to the engine in a coherent way.

however! its very easy to make custom events so you can just do something like

```
case 'Play Stage Animation':
         stageBuild.object.animation.play("anim");
```

**Comment by iamteles** [comment]
maybe if we were to add softcoded stages using JSONs [(see the source code for Characteristic Disparity)](https://github.com/iamteles/Characteristic-Disparity-V2/blob/main/source/gameObjects/Stage.hx) it could be more feasible but we have already decided against it so you're out of luck

**Comment by HTGM1** [comment]
as long as there is something similar to make something work, i was thinking something to do on the way of hard coding things to do it, like have a stage setup with animations already and do something like you just described to play back a named animation

i really do appreciate the insight tho thank you for the clarifications on how things are currently structured, i think i know what to do to make stuff work, basically i was thinking of stuff when i start working on code for a project that requires stage porting work and rework things as timed animations with the chart

also don't worry its all good about softcoded stages, this project seems to be aiming a different goal that's more towards hardcoding anyways, reason why i want to work in this, to better familiarize myself with haxe, especially with how easy it is to read then other FnF engine source code wise (for my needs anyways)

besides thinking about softcoded stages could be limiting on how fast everything loads as well as other issues that can be caused in the process of doing so (especially stage switching stuff I'd imagine)

if i think of other ideas ill post them, this one was just one of the ones i thought of while trying to look at how stages and events are setup thinking how to properly port some of my own stages (main project wise) or base game stages (side project wise) over with animations setup to still work fine
