### ISSUE TITLE
is there a proper way to do a ATLAS sprite outside of characters?

### ISSUE THREAD

**Issue by HTGM1** [DoidoTeam/FNF-Doido-Engine#17]
### What is your question?

just a general curiosity question, is there a proper way to do a ATLAS sprite outside of characters?

because there are some scenarios where i want to do that for a few things, if not that is fine, just mostly poking through the files while also trying to use my knowledge of what Ive gained so far to see if it was possible

**Comment by iamteles** [comment]
you could do something like

```
var sprite = new FlxAnimate();
sprite.isAnimateAtlas = true;
sprite.loadAtlas(Paths.getPath('images/sprite'));
sprite.showPivot = false;
sprite.anim.addBySymbol("idle", "symbol", 24, false);
sprite.anim.play("idle");
add(sprite);
```

just keep in mind you have to use FlxAnimate instead of FlxSprite and animations are accessed by `anim` instead of `animation'. (also dont forget to set `isAnimateAtlas` to true and `showPivot` to false

**Comment by HTGM1** [comment]
what if it creates a Null Object Reference, the state i want it to be in, been restructuring this a few times and it results in the same issue every time

the state i'm trying to currently do this on is titleState
![Screenshot 2024-11-02 174409](https://github.com/user-attachments/assets/cd2a6fcd-18c4-46f7-a6b9-aadb4c4687df)
![Screenshot 2024-11-02 174421](https://github.com/user-attachments/assets/ff7bd89c-59ff-4415-b01e-2d6840a7a4f1)

**Comment by HTGM1** [comment]
i did rename the one in the curBeat part of the code as well from animate to anim

**Comment by HTGM1** [comment]
wait, nvm fixed it, i am stupid
