### ISSUE TITLE
setting up a ATLAS gf at titleState (follow up to issue #17)

### ISSUE THREAD

**Issue by HTGM1** [DoidoTeam/FNF-Doido-Engine#18]
### What is your question?

been trying to look at this for a few days now and Ive been having issues figuring out a proper way to do this for the atlas GF i replaced the normal GF with at titleState

![Screenshot 2024-11-04 222958](https://github.com/user-attachments/assets/7c3a0b54-4526-470a-9df8-a1d3ea40336a)

how i have it currently says there isn't a field for curAnim in FlxAnimate and I've been looking at it's stuff to find a suitable way to do something similar to how it was before as I'm not coming across much documentation other then me browsing the files for FlxAnimate, usually this is where i try to find a hacky workaround that makes it work, but nothing i have been doing poking about has been working as of the moment

this is mostly a throw away question, if there is no solution here then i can just easily revert the stuff i was doing for the title state as the stuff i learned from the last issue did help me setup something for the loading state to make it more lively

**Comment by iamteles** [comment]
we are currently looking for a solution to make this (and animated sprites in general, including offsets and stuff) simpler which would either involve changing flxanimate-doido or creating a new class entirely

**Comment by HTGM1** [comment]
in which i did find out from the terminal, reason for looking for a alternative workaround, which honestly i wonder why my brain didn't about doing a string variable, this one was specifically for the smaller remaster project, but this will help me for other situations where i need something done like this

hopefully whenever animation stuff does become simpler i can come back to all this ATLAS code and rework it, but for now what I've been learning here gets the job done!
