### ISSUE TITLE
error before compile

### ISSUE THREAD

**Issue by Przemek20211** [DoidoTeam/FNF-Doido-Engine#6]
i want to compile the game but i'm getting this error

Standard library not found. You may need to set your `HAXE_STD_PATH` environment variable

can someone help me 

![png](https://github.com/user-attachments/assets/aed3644e-1a25-46bc-8e0a-9ca1db177609)

**Comment by iamteles** [comment]
try reinstalling haxe

**Comment by Przemek20211** [comment]
i got that error now 

![png2](https://github.com/user-attachments/assets/4cb31a6d-a33e-4939-ab25-30931cd0760a)

**Comment by iamteles** [comment]
download the latest version of the source code and run this command on cmd
```
haxelib git flxanimate-doido https://github.com/DoidoTeam/flxanimate-doido
```

**Comment by iamteles** [comment]
if you dont wanna redownload the engine you can go into Project.xml and change from `<haxelib name="flxanimate"/>` to `<haxelib name="flxanimate-doido"/>`
