### ISSUE TITLE
I can't add characters.

### ISSUE THREAD

**Issue by Pixemated** [DoidoTeam/FNF-Doido-Engine#7]
When I try to add characters it appears as the face guy and doesn't load the character I am trying to put

**Comment by iamteles** [comment]
How are you adding the character?

**Comment by Pixemated** [comment]
assets < images < characters i add a folder and put the xml and png in there that uses spritesheet and xml generator and put my character in there and in the character editor its not thre

**Comment by Pixemated** [comment]
oh yea and also in the source code i put the character name in there too (i also added the icons)

**Comment by iamteles** [comment]
if you added the character to the Character.hx class you need to add it to CoolUtil's charList array

**Comment by Pixemated** [comment]
> if you added the character to the Character.hx class you need to add it to CoolUtil's charList array

i put it in both and it still doesn't show up
