### ISSUE TITLE
discord rpc compile error

### ISSUE THREAD

**Issue by AnotherPlayer8** [DoidoTeam/FNF-Doido-Engine#8]
### Describe your problem here.

whenever i try to compile the game, this error appears.
i have the correct hxdiscord_rpc version, but it doesn't work
how can i fix that??
![Screenshot 2024-10-07 224504](https://github.com/user-attachments/assets/62c765c8-14fb-437e-9d19-5bda5f80a574)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i didn't edit anything in the build

**Comment by iamteles** [comment]
have you tried reinstalling hxdiscord_rpc? if you have, you could also try doing `haxelib install hxdiscord_rpc 1.2.4`
